#plot 4 (data already loaded)
par(mfrow = c(2,2))
plot(data$Time, data$Global_active_power, type = "l", xlab ="", ylab = "Global Active Power (kilowatts)")
plot(data$Time, data$Voltage, type = "l", xlab ="datetime", ylab = "Voltage")
plot(data$Time, data$Sub_metering_1, type = "l", xlab ="", ylab = "Energy sub metering")
points(data$Time, data$Sub_metering_2, col = "red", type = "l")
points(data$Time, data$Sub_metering_3, col = "blue", type = "l")
legend("topright", pch = "_" , col = c("black", "red", "blue"), legend = names(data)[7:9], bty = "n", xjust = 1)
plot(data$Time, data$Global_reactive_power, type = "l", xlab ="datetime", ylab = "Global_reactive_power")
dev.copy(png, file = "plot4.png")
dev.off()